### ISSUE TITLE
PostCSS 6 compat

### ISSUE THREAD

**Issue by MoOx** [axa-ch/postcss-pseudoelements#12]
Any plan to bump postcss deps?
Should be easy as there is not a lot of breaking changes :)

**Comment by davidknezic** [comment]
Sure, will have a look at that soon.

**Comment by MoOx** [comment]
Do you need a hand for this?

**Comment by sventschui** [comment]
Done in `5.0.0`

**Comment by davidknezic** [comment]
Thx @sventschui.
