### ISSUE TITLE
Why output both double and single colons?

### ISSUE THREAD

**Issue by davidtheclark** [axa-ch/postcss-pseudoelements#2]
Why not just output the single colons only, as that will be understood by all browsers? Curious if there's a reason.

**Comment by sventschui** [comment]
Well it is currently supported by all major browsers but it is not standard compliant and therefore not future proof

**Comment by davidtheclark** [comment]
Would you be open to a PR adding an option to generate single-colon selectors only? I don't need the extra.

**Comment by sventschui** [comment]
Yes for sure, go ahead

**Comment by sventschui** [comment]
This would also add support for IE 8, you could mention this in the readme.

IE 8 ignores any ruleset that has a double colon in one of the selectors:

``` css
.foo::after,
.foo:after {
  // will not work in IE 8
}
```

**Comment by davidtheclark** [comment]
You're right ... so ... if the _only_ reason to add the single-colon version is to support IE8 (right? — seems it's [the only browser that doesn't support double-colon](http://caniuse.com/#search=%3A%3Abefore)); but the current output (double then single in one selector) right now _breaks in IE8_ — isn't that paradoxical? What is the situation where you would want the current output? Isn't the _only_ use-case for this plugin (supporting IE8) to output single-colon only?

**Comment by sventschui** [comment]
You're right. I'll do an update

**Comment by sventschui** [comment]
Fixed with v 2.0

**Comment by davidtheclark** [comment]
Cool, thanks.
