### ISSUE TITLE
Send PR to PostCSS README.md

### ISSUE THREAD

**Issue by ai** [axa-ch/postcss-pseudoelements#3]
1. Please add `ChangeLog.md`. Every PostCSS plgin should have it.
2. Please add yor plugin to PostCSS README.md in `v4.1` branch.

**Comment by sventschui** [comment]
See postcss/postcss#256

**Comment by ai** [comment]
Don't forget about ChangeLog. It will be in future mandatory plugin guidelines.

**Comment by sventschui** [comment]
Already added a ChangeLog file
